#---
#version: 2
#updates:
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    assignees:
#      - "TomerFi"
#    labels:
#      - "type: dependencies"
#    commit-message:
#      prefix: "ci"
#      include: "scope"
