---
name: Hebcal-API Released

on:
  repository_dispatch:
    types: [hebcal-api-released]

jobs:
  update_shabbat_times_script:
    runs-on: ubuntu-latest
    environment: deployment
    name: Update shabbat_times script with new Hebcal-API version
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Get new version from the event
        id: new_version
        run: echo "::set-output name=text::${{ github.event.client_payload.release }}" | xargs

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update shabbat_times script
        run:
          sed -i 's/\/\/DEPS info.tomfi.hebcal:hebcal-api:.*/\/\/DEPS info.tomfi.hebcal:hebcal-api:${{ steps.new_version.outputs.text }}/g;
          s/version = .*\,/version = "${{ steps.new_version.outputs.text }}",/g' src/shabbat_times.java

      - name: Commit and push back to repository
        run: |
          git add src/shabbat_times.java
          git commit -m "build(deps): bumped hebcal-api to ${{ steps.new_version.outputs.text }}"
          git push
