---
name: Lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint project
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVA: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
